DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS result;
DROP TABLE IF EXISTS link;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE game (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    datestamp DATE NOT NULL DEFAULT CURRENT_DATE,
    map TEXT,
    winner INTEGER,
    FOREIGN KEY (winner) REFERENCES user (id)
);

CREATE TABLE result (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    game_id INTEGER NOT NULL,
    score INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id),
    FOREIGN KEY (game_id) REFERENCES game (id)
);

CREATE TABLE link (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL,
    map_hash TEXT NOT NULL,
    game_hash TEXT NOT NULL,
    FOREIGN KEY (game_id) REFERENCES game (id)
);